[build]
  publish = "."
  command = ""

# Cache control headers for beta landing page
[[headers]]
  for = "/beta/index.html"
  [headers.values]
    Cache-Control = "no-store, must-revalidate"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/beta/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/beta/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Proxy all API calls to the Render API
[[redirects]]
  from = "/api/*"
  to   = "https://api.getbrikk.com/api/:splat"
  status = 200
  force  = true

# SPA fallback for beta subdirectory
[[redirects]]
  from = "/beta/*"
  to = "/beta/index.html"
  status = 200

# Nice URLs for checkout helper pages
[[redirects]]
  from = "/checkout/success"
  to   = "/public/checkout/success.html"
  status = 200

[[redirects]]
  from = "/checkout/cancel"
  to   = "/public/checkout/cancel.html"
  status = 200

# Environment variables (can be overridden in Netlify dashboard)
[build.environment]
  API_BASE = "https://brikk-infrastructure.onrender.com"

