[build]
  publish = "."
  command = "echo 'Static site - no build needed'"

# Cache control headers
[[headers]]
  for = "/beta/index.html"
  [headers.values]
    Cache-Control = "no-store, must-revalidate"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/beta/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/beta/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# SPA fallback for beta subdirectory
[[redirects]]
  from = "/beta/*"
  to = "/beta/index.html"
  status = 200

# Environment variables (can be overridden in Netlify dashboard)
[build.environment]
  API_BASE = "https://brikk-infrastructure.onrender.com"

