[build]
publish = "."
command = ""

# Proxy all API calls to the Render API
[[redirects]]
from = "/api/*"
to   = "https://api.getbrikk.com/api/:splat"
status = 200
force  = true

# Nice URLs for checkout helper pages if you keep them under /public/checkout
[[redirects]]
from = "/checkout/success"
to   = "/public/checkout/success.html"
status = 200

[[redirects]]
from = "/checkout/cancel"
to   = "/public/checkout/cancel.html"
status = 200
